# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FuelPump' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FuelPump
  pod 'SwiftLint', '~> 0.50.3'
  pod 'RealmSwift', '~> 10'

end
